version: "3.9"

networks:
  app_network:
    driver: bridge

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_PROTOCOL=http
      - REACT_APP_API_HOST=localhost
      - REACT_APP_API_PORT=8081
    networks:
      - app_network