version: "3.9"

networks:
  app_network:
    driver: bridge

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: katalogpsow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./backend/src/main/resources/static:/app/resources/static
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_PROTOCOL=http
      - REACT_APP_API_HOST=app
      - REACT_APP_API_PORT=8081
    depends_on:
      - app
    networks:
      - app_network

volumes:
  postgres-data:
